/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_final.view;
import com.mycompany.projeto_final.controller.AlunoController;
import com.mycompany.projeto_final.service.AlunoService;
import com.mycompany.projeto_final.domain.Aluno;
import com.mycompany.projeto_final.domain.AlunoRequestDTO;
import com.mycompany.projeto_final.domain.AlunoResponseDTO;
import com.mycompany.projeto_final.exception.AlunoJaCadastradoException;
import com.mycompany.projeto_final.exception.AlunoNaoEncontradoException;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.plaf.OptionPaneUI;
import javax.swing.text.MaskFormatter;


public class JanelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaInicial.class.getName());
   
    public JanelaInicial() {
        initComponents();
        textConsultarAluno.setText("MATRICULA");
        textConsultarAluno.setForeground(Color.GRAY);
        textFieldRemoverALuno.setText("MATRICULA");
        textFieldRemoverALuno.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelPrincipal = new javax.swing.JPanel();
        Aluno = new javax.swing.JButton();
        tituloPrincipal = new javax.swing.JLabel();
        painelAluno = new javax.swing.JPanel();
        voltarDeAluno = new javax.swing.JButton();
        labelMatricula = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelDataDeNascimento = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        textMatricula = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        cadastrarAluno = new javax.swing.JButton();
        textConsultarAluno = new javax.swing.JTextField();
        consultarAluno = new javax.swing.JButton();
        totalAlunos = new javax.swing.JButton();
        forformattedTextFieldDataDeNascimento = new javax.swing.JFormattedTextField();
        botaoAlunoMaisVelho = new javax.swing.JButton();
        botaoAlunoMaisNovo = new javax.swing.JButton();
        formattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        formattedTextFieldCpf = new javax.swing.JFormattedTextField();
        buttonRemoverAluno = new javax.swing.JButton();
        textFieldRemoverALuno = new javax.swing.JTextField();
        botaoAdicionarNaPosição = new javax.swing.JButton();
        textFieldAdicionarNaPosição = new javax.swing.JTextField();
        botaoTabelaAlunos = new javax.swing.JButton();
        painelTabela = new javax.swing.JPanel();
        botaoVoltarDaTabela = new javax.swing.JButton();
        scrollPaneDaTabela = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Aluno.setText("Aluno");
        Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoActionPerformed(evt);
            }
        });

        tituloPrincipal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tituloPrincipal.setText("Sistema de Gerenciamento de Aluno");

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Aluno))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(Aluno)
                .addGap(29, 29, 29))
        );

        getContentPane().add(painelPrincipal, "painelPrincipal");

        voltarDeAluno.setText("Voltar");
        voltarDeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarDeAlunoActionPerformed(evt);
            }
        });

        labelMatricula.setText("MATRICULA:");

        labelNome.setText("NOME:");

        labelCpf.setText("CPF:");

        labelDataDeNascimento.setText("DATA DE NASCIMENTO:");

        labelTelefone.setText("TELEFONE:");

        cadastrarAluno.setText("ADICIONAR ALUNO");
        cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoActionPerformed(evt);
            }
        });

        textConsultarAluno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textConsultarAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textConsultarAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textConsultarAlunoFocusLost(evt);
            }
        });
        textConsultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConsultarAlunoActionPerformed(evt);
            }
        });

        consultarAluno.setText("CONSULTAR");
        consultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAlunoActionPerformed(evt);
            }
        });

        totalAlunos.setText("TOTAL ALUNOS");
        totalAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAlunosActionPerformed(evt);
            }
        });

        try {
            forformattedTextFieldDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        forformattedTextFieldDataDeNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                forformattedTextFieldDataDeNascimentoFocusGained(evt);
            }
        });
        forformattedTextFieldDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forformattedTextFieldDataDeNascimentoActionPerformed(evt);
            }
        });

        botaoAlunoMaisVelho.setText("ALUNO MAIS VELHO");
        botaoAlunoMaisVelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunoMaisVelhoActionPerformed(evt);
            }
        });

        botaoAlunoMaisNovo.setText("ALUNO MAIS NOVO");
        botaoAlunoMaisNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunoMaisNovoActionPerformed(evt);
            }
        });

        try {
            formattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTextFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formattedTextFieldTelefoneFocusGained(evt);
            }
        });
        formattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTextFieldTelefoneActionPerformed(evt);
            }
        });

        try {
            formattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTextFieldCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formattedTextFieldCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formattedTextFieldCpfFocusLost(evt);
            }
        });
        formattedTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTextFieldCpfActionPerformed(evt);
            }
        });

        buttonRemoverAluno.setText("REMOVER ");
        buttonRemoverAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverAlunoActionPerformed(evt);
            }
        });

        textFieldRemoverALuno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldRemoverALuno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldRemoverALunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldRemoverALunoFocusLost(evt);
            }
        });
        textFieldRemoverALuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRemoverALunoActionPerformed(evt);
            }
        });

        botaoAdicionarNaPosição.setText("ADICIONAR NA Pº:");
        botaoAdicionarNaPosição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarNaPosiçãoActionPerformed(evt);
            }
        });

        textFieldAdicionarNaPosição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAdicionarNaPosiçãoActionPerformed(evt);
            }
        });

        botaoTabelaAlunos.setText("TABELA ALUNOS");
        botaoTabelaAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTabelaAlunosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAlunoLayout = new javax.swing.GroupLayout(painelAluno);
        painelAluno.setLayout(painelAlunoLayout);
        painelAlunoLayout.setHorizontalGroup(
            painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAlunoLayout.createSequentialGroup()
                        .addComponent(labelDataDeNascimento)
                        .addGap(18, 18, 18)
                        .addComponent(forformattedTextFieldDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAlunoLayout.createSequentialGroup()
                        .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAlunoLayout.createSequentialGroup()
                                .addComponent(labelCpf)
                                .addGap(18, 18, 18)
                                .addComponent(formattedTextFieldCpf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAlunoLayout.createSequentialGroup()
                                .addComponent(labelTelefone)
                                .addGap(18, 18, 18)
                                .addComponent(formattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAlunoLayout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAlunoLayout.createSequentialGroup()
                                .addComponent(voltarDeAluno)
                                .addGap(18, 18, 18)
                                .addComponent(cadastrarAluno)))
                        .addGap(18, 18, 18)
                        .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlunoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldRemoverALuno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlunoLayout.createSequentialGroup()
                                        .addComponent(botaoAdicionarNaPosição)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldAdicionarNaPosição, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(painelAlunoLayout.createSequentialGroup()
                                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botaoTabelaAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoAlunoMaisNovo)
                                    .addComponent(botaoAlunoMaisVelho))
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlunoLayout.createSequentialGroup()
                        .addComponent(labelMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelAlunoLayout.createSequentialGroup()
                                .addComponent(consultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        painelAlunoLayout.setVerticalGroup(
            painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlunoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarAluno))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRemoverALuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRemoverAluno))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(formattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarNaPosição)
                    .addComponent(textFieldAdicionarNaPosição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDeNascimento)
                    .addComponent(forformattedTextFieldDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTelefone)
                    .addComponent(formattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlunoMaisVelho)
                    .addComponent(botaoTabelaAlunos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarDeAluno)
                    .addComponent(cadastrarAluno)
                    .addComponent(totalAlunos)
                    .addComponent(botaoAlunoMaisNovo))
                .addGap(19, 19, 19))
        );

        getContentPane().add(painelAluno, "painelAluno");

        botaoVoltarDaTabela.setText("VOLTAR");
        botaoVoltarDaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarDaTabelaActionPerformed(evt);
            }
        });

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneDaTabela.setViewportView(tabelaAlunos);

        javax.swing.GroupLayout painelTabelaLayout = new javax.swing.GroupLayout(painelTabela);
        painelTabela.setLayout(painelTabelaLayout);
        painelTabelaLayout.setHorizontalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoVoltarDaTabela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addComponent(scrollPaneDaTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelTabelaLayout.setVerticalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneDaTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botaoVoltarDaTabela)
                .addGap(27, 27, 27))
        );

        getContentPane().add(painelTabela, "painelTabela");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(),"painelAluno");
        // TODO add your handling code here:
    }//GEN-LAST:event_AlunoActionPerformed

    private void voltarDeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarDeAlunoActionPerformed
       CardLayout a = (CardLayout) getContentPane().getLayout();
       a.show(getContentPane(),"painelPrincipal");
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarDeAlunoActionPerformed

    private void cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoActionPerformed
        try {
            String dataDeNascimento = forformattedTextFieldDataDeNascimento.getText();
            DateTimeFormatter dTF = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate localDate = LocalDate.parse(dataDeNascimento, dTF);
            
            AlunoRequestDTO dadosAluno = new AlunoRequestDTO(textMatricula.getText(), textNome.getText(),
                                                        localDate, formattedTextFieldCpf.getText(),
                                                        formattedTextFieldTelefone.getText());
            AlunoController.cadastrarAluno(dadosAluno);
            String mensagem = "ALUNO CADASTRADO";
            JOptionPane.showMessageDialog(this, mensagem, "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        } catch(IllegalArgumentException | AlunoJaCadastradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_cadastrarAlunoActionPerformed

    private void textConsultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConsultarAlunoActionPerformed
       
    }//GEN-LAST:event_textConsultarAlunoActionPerformed

    private void consultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAlunoActionPerformed
        try {
            String matricula = textConsultarAluno.getText().trim();
            AlunoResponseDTO dadosAluno = AlunoController.consultarAluno(matricula);
            LocalDate date = LocalDate.parse(dadosAluno.dataNascimento().toString());
            DateTimeFormatter dTF = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String dataDeNascimento = date.format(dTF);
            String mensagem = "ALUNO CONSULTADO: \n" +
                              "MATRÍCULA: " + dadosAluno.matricula() + "\n" +
                              "NOME: " + dadosAluno.nome() + "\n" + 
                              "CPF: " + dadosAluno.cpf() + "\n" + 
                              "DATA DE NASCIMENTO: " + dataDeNascimento.toString() + "\n" + 
                              "TELEFONE: " + dadosAluno.telefone() + "\n" + 
                              "IDADE: " + dadosAluno.idade();
            JOptionPane.showMessageDialog(this, mensagem, "INFORMATIVO",JOptionPane.INFORMATION_MESSAGE);
        } catch(IllegalArgumentException | AlunoNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_consultarAlunoActionPerformed

    private void totalAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAlunosActionPerformed
       Integer quantidade = AlunoController.quantidadeTotalDeAlunos();
       JOptionPane.showMessageDialog(this, quantidade.toString(), "QUANTIDADE DE ALUNOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_totalAlunosActionPerformed

    private void forformattedTextFieldDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forformattedTextFieldDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forformattedTextFieldDataDeNascimentoActionPerformed

    private void botaoAlunoMaisNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunoMaisNovoActionPerformed
         try {
            if(AlunoController.maisNovo() != null)  {
            Aluno aluno = AlunoController.maisNovo();
            AlunoResponseDTO dadosAluno = AlunoController.consultarAluno(aluno.getMatricula());
            String mensagem = "ALUNO MAIS NOVO: \n" +
                              "MATRÍCULA: " + dadosAluno.matricula() + "\n" +
                              "NOME: " + dadosAluno.nome() + "\n" + 
                              "CPF: " + dadosAluno.cpf() + "\n" + 
                              "DATA DE NASCIMENTO: " + dadosAluno.dataNascimento().toString() + "\n" + 
                              "TELEFONE: " + dadosAluno.telefone() + "\n" + 
                              "IDADE: " + dadosAluno.idade();
            JOptionPane.showMessageDialog(this, mensagem, "DADOS ALUNO: ",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,"MATRICULA INEXISTENTE","INFORMATIVO",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(AlunoNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAlunoMaisNovoActionPerformed

    private void botaoAlunoMaisVelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunoMaisVelhoActionPerformed
     
        try {
            if(AlunoController.maisVelho() != null)  {
            Aluno aluno = AlunoController.maisVelho();
            AlunoResponseDTO dadosAluno = AlunoController.consultarAluno(aluno.getMatricula());
            String mensagem = "ALUNO MAIS VELHO: \n" +
                              "MATRÍCULA: " + dadosAluno.matricula() + "\n" +
                              "NOME: " + dadosAluno.nome() + "\n" + 
                              "CPF: " + dadosAluno.cpf() + "\n" + 
                              "DATA DE NASCIMENTO: " + dadosAluno.dataNascimento().toString() + "\n" + 
                              "TELEFONE: " + dadosAluno.telefone() + "\n" + 
                              "IDADE: " + dadosAluno.idade();
            JOptionPane.showMessageDialog(this, mensagem, "DADOS ALUNO: ",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,"Não existe nenhuma matricula","INFORMATIVO",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(AlunoNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_botaoAlunoMaisVelhoActionPerformed

    private void formattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTextFieldTelefoneActionPerformed

    private void formattedTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTextFieldCpfActionPerformed

    private void buttonRemoverAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverAlunoActionPerformed
        try {
            AlunoController.removerAluno(textFieldRemoverALuno.getText());
            JOptionPane.showMessageDialog(this, "ALUNO REMOVIDO", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        } catch(IllegalArgumentException | AlunoNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonRemoverAlunoActionPerformed

    private void textConsultarAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textConsultarAlunoFocusLost
        if (textConsultarAluno.getText().isEmpty()) {
            textConsultarAluno.setForeground(Color.GRAY);
            textConsultarAluno.setText("MATRICULA");
}

    }//GEN-LAST:event_textConsultarAlunoFocusLost

    private void textConsultarAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textConsultarAlunoFocusGained
        if (textConsultarAluno.getText().equals("MATRICULA")) {
            textConsultarAluno.setText("");
            textConsultarAluno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textConsultarAlunoFocusGained

    private void textFieldRemoverALunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldRemoverALunoFocusGained
        if(textFieldRemoverALuno.getText().equals("MATRICULA")) {
            textFieldRemoverALuno.setText("");
            textFieldRemoverALuno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textFieldRemoverALunoFocusGained

    private void textFieldRemoverALunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldRemoverALunoFocusLost
        if(textFieldRemoverALuno.getText().isEmpty()) {
            textFieldRemoverALuno.setForeground(Color.GRAY);
            textFieldRemoverALuno.setText("MATRICULA");
        }
    }//GEN-LAST:event_textFieldRemoverALunoFocusLost

    private void formattedTextFieldTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTextFieldTelefoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTextFieldTelefoneFocusGained

    private void textFieldRemoverALunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRemoverALunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRemoverALunoActionPerformed

    private void forformattedTextFieldDataDeNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_forformattedTextFieldDataDeNascimentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_forformattedTextFieldDataDeNascimentoFocusGained

    private void formattedTextFieldCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTextFieldCpfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTextFieldCpfFocusGained

    private void formattedTextFieldCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTextFieldCpfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTextFieldCpfFocusLost

    private void textFieldAdicionarNaPosiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAdicionarNaPosiçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAdicionarNaPosiçãoActionPerformed

    private void botaoAdicionarNaPosiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarNaPosiçãoActionPerformed
       
        try {
            String StrPosicao = textFieldAdicionarNaPosição.getText().trim();
            if(StrPosicao ==null || StrPosicao.isEmpty()) {
                JOptionPane.showMessageDialog(this,"A posição esta vazia,por favor insira uma posição","Erro",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(!StrPosicao.matches("\\d+")) {
                JOptionPane.showMessageDialog(this,"É necessario o campo ser composto somente por numeros.","Erro",JOptionPane.ERROR_MESSAGE);
                return;
            }
            int posicao = Integer.parseInt(StrPosicao);
            
            if(posicao > AlunoController.quantidadeTotalDeAlunos()) {
                JOptionPane.showMessageDialog(this,"A posição é maior que o tamanho da lista","Erro",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String dataDeNascimento = forformattedTextFieldDataDeNascimento.getText();
            DateTimeFormatter dTF = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate localDate = LocalDate.parse(dataDeNascimento, dTF);
            
            AlunoRequestDTO dadosAluno = new AlunoRequestDTO(textMatricula.getText(), textNome.getText(),
                                                        localDate, formattedTextFieldCpf.getText(),
                                                        formattedTextFieldTelefone.getText());
            AlunoController.cadastrarAlunoNaPosicao(dadosAluno,posicao);
            String mensagem = "ALUNO CADASTRADO";
            JOptionPane.showMessageDialog(this, mensagem, "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        } catch(IllegalArgumentException | AlunoJaCadastradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAdicionarNaPosiçãoActionPerformed

    private void botaoTabelaAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTabelaAlunosActionPerformed
        
        AlunoController.popularTabelaAlunos(tabelaAlunos);
        
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(),"painelTabela");
// TODO add your handling code here:
    }//GEN-LAST:event_botaoTabelaAlunosActionPerformed

    private void botaoVoltarDaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarDaTabelaActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(),"painelAluno");
// TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltarDaTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JanelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aluno;
    private javax.swing.JButton botaoAdicionarNaPosição;
    private javax.swing.JButton botaoAlunoMaisNovo;
    private javax.swing.JButton botaoAlunoMaisVelho;
    private javax.swing.JButton botaoTabelaAlunos;
    private javax.swing.JButton botaoVoltarDaTabela;
    private javax.swing.JButton buttonRemoverAluno;
    private javax.swing.JButton cadastrarAluno;
    private javax.swing.JButton consultarAluno;
    private javax.swing.JFormattedTextField forformattedTextFieldDataDeNascimento;
    private javax.swing.JFormattedTextField formattedTextFieldCpf;
    private javax.swing.JFormattedTextField formattedTextFieldTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDataDeNascimento;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel painelAluno;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JScrollPane scrollPaneDaTabela;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTextField textConsultarAluno;
    private javax.swing.JTextField textFieldAdicionarNaPosição;
    private javax.swing.JTextField textFieldRemoverALuno;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNome;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JButton totalAlunos;
    private javax.swing.JButton voltarDeAluno;
    // End of variables declaration//GEN-END:variables
}
