/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_final.view;
import com.mycompany.projeto_final.Aluno;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author moise
 */
public class JanelaInicial extends javax.swing.JFrame {
    
    
    List<Aluno> alunos;
    /**
     * Creates new form JanelaInicial
     */
    public JanelaInicial() {
        alunos = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        Aluno = new javax.swing.JButton();
        tituloPrincipal = new javax.swing.JLabel();
        painelAluno = new javax.swing.JPanel();
        voltarDeAluno = new javax.swing.JButton();
        labelMatricula = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelDataDeNascimento = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        textMatricula = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textCpf = new javax.swing.JTextField();
        textDataDeNascimento = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        textIdade = new javax.swing.JTextField();
        adicionarAluno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Aluno.setText("Aluno");
        Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoActionPerformed(evt);
            }
        });

        tituloPrincipal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tituloPrincipal.setText("Sistema de Gerenciamento de Aluno");

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Aluno))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(Aluno)
                .addGap(29, 29, 29))
        );

        getContentPane().add(painelPrincipal, "painelPrincipal");

        voltarDeAluno.setText("Voltar");
        voltarDeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarDeAlunoActionPerformed(evt);
            }
        });

        labelMatricula.setText("MATRICULA:");

        labelNome.setText("NOME:");

        labelCpf.setText("CPF:");

        labelDataDeNascimento.setText("DATA DE NASCIMENTO:");

        labelTelefone.setText("TELEFONE:");

        labelIdade.setText("IDADE:");

        textCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfActionPerformed(evt);
            }
        });

        textDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataDeNascimentoActionPerformed(evt);
            }
        });

        adicionarAluno.setText("ADICIONAR ALUNO");
        adicionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAlunoLayout = new javax.swing.GroupLayout(painelAluno);
        painelAluno.setLayout(painelAlunoLayout);
        painelAlunoLayout.setHorizontalGroup(
            painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(painelAlunoLayout.createSequentialGroup()
                            .addComponent(labelIdade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelAlunoLayout.createSequentialGroup()
                            .addComponent(labelTelefone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelAlunoLayout.createSequentialGroup()
                            .addComponent(labelCpf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textCpf))
                        .addGroup(painelAlunoLayout.createSequentialGroup()
                            .addComponent(labelNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textNome))
                        .addGroup(painelAlunoLayout.createSequentialGroup()
                            .addComponent(labelMatricula)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelAlunoLayout.createSequentialGroup()
                            .addComponent(voltarDeAluno)
                            .addGap(18, 18, 18)
                            .addComponent(adicionarAluno)))
                    .addGroup(painelAlunoLayout.createSequentialGroup()
                        .addComponent(labelDataDeNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        painelAlunoLayout.setVerticalGroup(
            painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlunoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDeNascimento)
                    .addComponent(textDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdade)
                    .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarDeAluno)
                    .addComponent(adicionarAluno))
                .addGap(19, 19, 19))
        );

        getContentPane().add(painelAluno, "painelAluno");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(),"painelAluno");
        // TODO add your handling code here:
    }//GEN-LAST:event_AlunoActionPerformed

    private void voltarDeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarDeAlunoActionPerformed
       CardLayout a = (CardLayout) getContentPane().getLayout();
       a.show(getContentPane(),"painelPrincipal");
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarDeAlunoActionPerformed

    private void textDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataDeNascimentoActionPerformed

    private void textCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfActionPerformed

    private void adicionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAlunoActionPerformed
        try {
        String matricula = textMatricula.getText().trim();
        String nome = textNome.getText().trim(); // Adicionado .trim()
        String cpf = textCpf.getText().trim();
        String telefone = textTelefone.getText().trim();
        String idadeStr = textIdade.getText().trim();
        String dataDeNascimento = textDataDeNascimento.getText().trim();

        // Validações básicas
        if (matricula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro! A matrícula está vazia.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            textMatricula.requestFocus(); 
            return;
        }

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro! O nome está vazio.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            textNome.requestFocus();
            return;
        }

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro! O CPF está vazio.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            textCpf.requestFocus();
            return;
        }
        

        int idade = 0;
        if (idadeStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro! A idade está vazia.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            textIdade.requestFocus();
            return;
        } else {
            try {
                idade = Integer.parseInt(idadeStr);
                if (idade <= 0) { 
                    JOptionPane.showMessageDialog(this, "Erro! Idade inválida.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                    textIdade.requestFocus();
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Erro! A idade deve ser um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                textIdade.requestFocus();
                return;
            }
        }
        for(Aluno alunoExiste:alunos) {
            if(alunoExiste.getMatricula().equalsIgnoreCase(matricula)) {
                textMatricula.requestFocus();
                throw new Exception("Erro de matricula igual");
                
            }
        }

     
        Aluno aluno = new Aluno(nome,matricula,dataDeNascimento,telefone,cpf,idade);
        alunos.add(aluno);
         String dadosAluno = String.format("Aluno Adicionado:\nMatrícula: %s\nNome: %s\nCPF: %s\nData Nasc: %s\nTelefone: %s\nIdade: %d",
                matricula, nome, cpf, dataDeNascimento, telefone, idade);
        JOptionPane.showMessageDialog(this,dadosAluno, "Sucesso", JOptionPane.INFORMATION_MESSAGE);

      
        textMatricula.setText("");
        textNome.setText("");
        textCpf.setText("");
        textDataDeNascimento.setText("");
        textTelefone.setText("");
        textIdade.setText("");
        textMatricula.requestFocus(); 

    } catch (Exception e) { 
        JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro Crítico", JOptionPane.ERROR_MESSAGE);
        
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JanelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aluno;
    private javax.swing.JButton adicionarAluno;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDataDeNascimento;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel painelAluno;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textDataDeNascimento;
    private javax.swing.JTextField textIdade;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelefone;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JButton voltarDeAluno;
    // End of variables declaration//GEN-END:variables
}
