/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_final.view;
import com.mycompany.projeto_final.controller.AlunoController;
import com.mycompany.projeto_final.service.AlunoService;
import com.mycompany.projeto_final.domain.Aluno;
import com.mycompany.projeto_final.domain.AlunoRequestDTO;
import com.mycompany.projeto_final.domain.AlunoResponseDTO;
import com.mycompany.projeto_final.exception.AlunoJaCadastradoException;
import com.mycompany.projeto_final.exception.AlunoNaoEncontradoException;
import java.awt.CardLayout;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;

public class JanelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaInicial.class.getName());
   
    public JanelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        Aluno = new javax.swing.JButton();
        tituloPrincipal = new javax.swing.JLabel();
        painelAluno = new javax.swing.JPanel();
        voltarDeAluno = new javax.swing.JButton();
        labelMatricula = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelDataDeNascimento = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        textMatricula = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textCpf = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        cadastrarAluno = new javax.swing.JButton();
        labelConsultarAluno = new javax.swing.JLabel();
        textConsultarAluno = new javax.swing.JTextField();
        consultarAluno = new javax.swing.JButton();
        totalAlunos = new javax.swing.JButton();
        formattedTextFieldDataDeNascimento = new javax.swing.JFormattedTextField();
        botaoAlunoMaisVelho = new javax.swing.JButton();
        botaoAlunoMaisNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Aluno.setText("Aluno");
        Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoActionPerformed(evt);
            }
        });

        tituloPrincipal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tituloPrincipal.setText("Sistema de Gerenciamento de Aluno");

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Aluno))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(Aluno)
                .addGap(29, 29, 29))
        );

        getContentPane().add(painelPrincipal, "painelPrincipal");

        voltarDeAluno.setText("Voltar");
        voltarDeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarDeAlunoActionPerformed(evt);
            }
        });

        labelMatricula.setText("MATRICULA:");

        labelNome.setText("NOME:");

        labelCpf.setText("CPF:");

        labelDataDeNascimento.setText("DATA DE NASCIMENTO:");

        labelTelefone.setText("TELEFONE:");

        textCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfActionPerformed(evt);
            }
        });

        cadastrarAluno.setText("ADICIONAR ALUNO");
        cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoActionPerformed(evt);
            }
        });

        labelConsultarAluno.setText("CONSULTAR ALUNO:");

        textConsultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConsultarAlunoActionPerformed(evt);
            }
        });

        consultarAluno.setText("CONSULTAR");
        consultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAlunoActionPerformed(evt);
            }
        });

        totalAlunos.setText("TOTAL ALUNOS");
        totalAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAlunosActionPerformed(evt);
            }
        });

        try {
            formattedTextFieldDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTextFieldDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTextFieldDataDeNascimentoActionPerformed(evt);
            }
        });

        botaoAlunoMaisVelho.setText("ALUNO MAIS VELHO");
        botaoAlunoMaisVelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunoMaisVelhoActionPerformed(evt);
            }
        });

        botaoAlunoMaisNovo.setText("ALUNO MAIS NOVO");
        botaoAlunoMaisNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunoMaisNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAlunoLayout = new javax.swing.GroupLayout(painelAluno);
        painelAluno.setLayout(painelAlunoLayout);
        painelAlunoLayout.setHorizontalGroup(
            painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAlunoLayout.createSequentialGroup()
                        .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelAlunoLayout.createSequentialGroup()
                                .addComponent(labelTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTelefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAlunoLayout.createSequentialGroup()
                                .addComponent(labelCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCpf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAlunoLayout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAlunoLayout.createSequentialGroup()
                                .addComponent(voltarDeAluno)
                                .addGap(18, 18, 18)
                                .addComponent(cadastrarAluno)))
                        .addGap(18, 18, 18)
                        .addComponent(totalAlunos))
                    .addGroup(painelAlunoLayout.createSequentialGroup()
                        .addComponent(labelMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(labelConsultarAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarAluno))
                    .addGroup(painelAlunoLayout.createSequentialGroup()
                        .addComponent(labelDataDeNascimento)
                        .addGap(18, 18, 18)
                        .addComponent(formattedTextFieldDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlunoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAlunoMaisNovo)
                    .addComponent(botaoAlunoMaisVelho))
                .addGap(33, 33, 33))
        );
        painelAlunoLayout.setVerticalGroup(
            painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlunoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConsultarAluno)
                    .addComponent(textConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarAluno))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDeNascimento)
                    .addComponent(formattedTextFieldDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(botaoAlunoMaisVelho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarDeAluno)
                    .addComponent(cadastrarAluno)
                    .addComponent(totalAlunos)
                    .addComponent(botaoAlunoMaisNovo))
                .addGap(19, 19, 19))
        );

        getContentPane().add(painelAluno, "painelAluno");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoActionPerformed
        CardLayout a = (CardLayout) getContentPane().getLayout();
        a.show(getContentPane(),"painelAluno");
        // TODO add your handling code here:
    }//GEN-LAST:event_AlunoActionPerformed

    private void voltarDeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarDeAlunoActionPerformed
       CardLayout a = (CardLayout) getContentPane().getLayout();
       a.show(getContentPane(),"painelPrincipal");
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarDeAlunoActionPerformed

    private void textCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfActionPerformed

    private void cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoActionPerformed
        try {
            String dataDeNascimento = formattedTextFieldDataDeNascimento.getText();
            DateTimeFormatter dTF = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            //data inserida e tranformada num LocalDate
            LocalDate localDate = LocalDate.parse(dataDeNascimento, dTF);
            
            AlunoRequestDTO dadosAluno = new AlunoRequestDTO(textMatricula.getText(), textNome.getText(),
                                                        localDate, textCpf.getText(),
                                                        textTelefone.getText());
            AlunoController.cadastrarAluno(dadosAluno);
            String mensagem = "ALUNO CADASTRADO";
            JOptionPane.showMessageDialog(this, mensagem, "RESULTADO", JOptionPane.INFORMATION_MESSAGE);
        } catch(IllegalArgumentException | AlunoJaCadastradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO AO CADASTRAR ALUNO", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_cadastrarAlunoActionPerformed

    private void textConsultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConsultarAlunoActionPerformed
       
    }//GEN-LAST:event_textConsultarAlunoActionPerformed

    private void consultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAlunoActionPerformed
        try {
            String matricula = textConsultarAluno.getText().trim();
            AlunoResponseDTO dadosAluno = AlunoController.consultarAluno(matricula);
            String mensagem = "ALUNO CONSULTADO: \n" +
                              "MATRÍCULA: " + dadosAluno.matricula() + "\n" +
                              "NOME: " + dadosAluno.nome() + "\n" + 
                              "CPF: " + dadosAluno.cpf() + "\n" + 
                              "DATA DE NASCIMENTO: " + dadosAluno.dataNascimento().toString() + "\n" + 
                              "TELEFONE: " + dadosAluno.telefone() + "\n" + 
                              "IDADE: " + dadosAluno.idade();
            JOptionPane.showMessageDialog(this, mensagem, "DADOS ALUNO: ",JOptionPane.INFORMATION_MESSAGE);
        } catch(AlunoNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO AO CONSULTAR ALUNO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_consultarAlunoActionPerformed

    private void totalAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAlunosActionPerformed
       Integer quantidade = AlunoController.quantidadeTotalDeAlunos();
       JOptionPane.showMessageDialog(this, quantidade.toString(), "QUANTIDADE DE ALUNOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_totalAlunosActionPerformed

    private void formattedTextFieldDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTextFieldDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTextFieldDataDeNascimentoActionPerformed

    private void botaoAlunoMaisNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunoMaisNovoActionPerformed
         try {
            if(AlunoController.maisNovo() != null)  {
            Aluno aluno = AlunoController.maisNovo();
            AlunoResponseDTO dadosAluno = AlunoController.consultarAluno(aluno.getMatricula());
            String mensagem = "ALUNO MAIS NOVO: \n" +
                              "MATRÍCULA: " + dadosAluno.matricula() + "\n" +
                              "NOME: " + dadosAluno.nome() + "\n" + 
                              "CPF: " + dadosAluno.cpf() + "\n" + 
                              "DATA DE NASCIMENTO: " + dadosAluno.dataNascimento().toString() + "\n" + 
                              "TELEFONE: " + dadosAluno.telefone() + "\n" + 
                              "IDADE: " + dadosAluno.idade();
            JOptionPane.showMessageDialog(this, mensagem, "DADOS ALUNO: ",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,"Não existe nenhuma matricula","Informativo",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(AlunoNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO AO CONSULTAR ALUNO", JOptionPane.INFORMATION_MESSAGE);
        }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAlunoMaisNovoActionPerformed

    private void botaoAlunoMaisVelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunoMaisVelhoActionPerformed
     
        try {
            if(AlunoController.maisVelho() != null)  {
            Aluno aluno = AlunoController.maisVelho();
            AlunoResponseDTO dadosAluno = AlunoController.consultarAluno(aluno.getMatricula());
            String mensagem = "ALUNO MAIS VELHO: \n" +
                              "MATRÍCULA: " + dadosAluno.matricula() + "\n" +
                              "NOME: " + dadosAluno.nome() + "\n" + 
                              "CPF: " + dadosAluno.cpf() + "\n" + 
                              "DATA DE NASCIMENTO: " + dadosAluno.dataNascimento().toString() + "\n" + 
                              "TELEFONE: " + dadosAluno.telefone() + "\n" + 
                              "IDADE: " + dadosAluno.idade();
            JOptionPane.showMessageDialog(this, mensagem, "DADOS ALUNO: ",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,"Não existe nenhuma matricula","Informativo",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(AlunoNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO AO CONSULTAR ALUNO", JOptionPane.INFORMATION_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_botaoAlunoMaisVelhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JanelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aluno;
    private javax.swing.JButton botaoAlunoMaisNovo;
    private javax.swing.JButton botaoAlunoMaisVelho;
    private javax.swing.JButton cadastrarAluno;
    private javax.swing.JButton consultarAluno;
    private javax.swing.JFormattedTextField formattedTextFieldDataDeNascimento;
    private javax.swing.JLabel labelConsultarAluno;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDataDeNascimento;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel painelAluno;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextField textConsultarAluno;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelefone;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JButton totalAlunos;
    private javax.swing.JButton voltarDeAluno;
    // End of variables declaration//GEN-END:variables
}
